In [35]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [63]:
from ssapp.data.AntennaDatasetLoaders import ReflectorCutDatasetComplex, ReflectorCutDataset
from torch.utils.data.dataloader import DataLoader
import torch

CUTS = 2
dataset_complex = ReflectorCutDatasetComplex(cuts = CUTS, mag_phase_transform=True)
dataset_simple = ReflectorCutDataset(cuts = CUTS)

complex_dataloader = DataLoader(dataset_complex)
dataloaderSimple = DataLoader(dataset_simple)







parameters tensor([[0.0100, 0.4000, 0.0000]])
Field Cuts: tensor([[[-3.9886e-02, -1.1229e-01, -2.5134e-16, -8.8881e-17],
         [-3.5864e-02, -1.1596e-01, -1.9664e-16, -6.0601e-17],
         [-3.1714e-02, -1.1944e-01, -2.4459e-16, -9.6585e-17],
         ...,
         [-3.1398e-02, -1.2380e-01,  1.0151e-16, -2.0273e-16],
         [-3.5598e-02, -1.2043e-01,  1.3699e-16, -2.8258e-16],
         [-3.9672e-02, -1.1689e-01,  5.6395e-17, -3.1269e-16]]])
tensor([[[1.1917e-01, 2.6659e-16],
         [1.2138e-01, 2.0577e-16],
         [1.2358e-01, 2.6297e-16],
         ...,
         [1.2772e-01, 2.2672e-16],
         [1.2558e-01, 3.1403e-16],
         [1.2344e-01, 3.1774e-16]]])
tensor([[[-1.9121, -2.8017],
         [-1.8708, -2.8426],
         [-1.8303, -2.7655],
         ...,
         [-1.8192, -1.1066],
         [-1.8582, -1.1194],
         [-1.8980, -1.3924]]])
parameters tensor([[0.0100, 0.4889, 0.0000]])
Field Cuts: tensor([[[-3.9886e-02, -1.1229e-01, -2.5134e-16, -8.8881e-17],
         [-

In [64]:
for parameters, mag, phase in iter(complex_dataloader):
    print('parameters',parameters)
    print(mag)
    print(phase)

parameters tensor([[0.0100, 0.4000, 0.0000]])
tensor([[[1.1917e-01, 2.6659e-16],
         [1.2138e-01, 2.0577e-16],
         [1.2358e-01, 2.6297e-16],
         ...,
         [1.2772e-01, 2.2672e-16],
         [1.2558e-01, 3.1403e-16],
         [1.2344e-01, 3.1774e-16]]])
tensor([[[-1.9121, -2.8017],
         [-1.8708, -2.8426],
         [-1.8303, -2.7655],
         ...,
         [-1.8192, -1.1066],
         [-1.8582, -1.1194],
         [-1.8980, -1.3924]]])
parameters tensor([[0.0100, 0.4889, 0.0000]])
tensor([[[1.0825e-01, 8.7676e-17],
         [1.1088e-01, 7.6471e-17],
         [1.1352e-01, 8.6348e-17],
         ...,
         [1.1430e-01, 2.9054e-16],
         [1.1170e-01, 2.6907e-16],
         [1.0911e-01, 3.1895e-16]]])
tensor([[[-0.7625, -2.7613],
         [-0.7191, -2.1574],
         [-0.6771, -1.7617],
         ...,
         [-0.6795, -2.6267],
         [-0.7214, -2.6651],
         [-0.7647, -2.6629]]])


In [48]:
from ssapp.data.AntennaDatasetLoaders import PatchAntennaDataset

test_dataset = PatchAntennaDataset(cuts = 1)




ValueError: Some errors were detected !
    Line #365 (got 7 columns instead of 4)
    Line #728 (got 7 columns instead of 4)